**🚀Linear Algebra -> Day 3**

**🚀 Introduction**

**Understanding vectors, matrices, norms, and tensors is essential for working with algorithms, optimization techniques, and modern AI frameworks.**

**The objective of this notebook is to understand and implement fundamental Linear Algebra concepts used in Data Science and AI, including vector norms, unit vectors, basis vectors, orthogonal vectors, matrices, and tensor representations. The notebook focuses on developing both conceptual understanding and practical coding skills using Python and NumPy.**

**📚 Notebook Consists Of**

- *Norms (L1, L2, and Infinity Norm)*
- *Unit Vectors*
- *Generalized Lp Norms*
- *Basis Vectors*
- *Orthogonal Vectors*
- *Matrices and Matrix Operations*
- *Generic Tensor Notation*
- *Higher-Rank Tensors*
- *NumPy Implementations*
- *Practice Examples and Outputs*
- *Key Learnings and Summary*

**🛠️ Tools & Libraries Used**

- *Python*
- *NumPy*
- *Jupyter Notebook*

📏**Norms**

1. *A norm is a mathematical function used to measure the length or magnitude of a vector.*
2. *Just as we measure the distance between two points, norms help us measure how large a vector is.*

In [1]:
import numpy as np

v = np.array([3,4])

print("Vector:", v)

Vector: [3 4]


**Why are Norms Important?**

Norms are widely used in:

- *Machine Learning*
- *Data Science*
- *Optimization*
- *Deep Learning*
- *Recommendation Systems*
- *Computer Vision*

*They help measure: Distance , Similarity , Error , Model Complexity*

**📏L1 Norm (Manhattan Distance)**

*The L1 norm is the sum of the absolute values of all vector elements.*

In [3]:
l1_norm = np.linalg.norm(v , ord=1)

print("L1 Norm:", l1_norm)

L1 Norm: 7.0


**📏L2 Norm (Euclidean Distance)**

*The L2 norm measures the straight-line distance from the origin to the vector.*

In [4]:
l2_norm = np.linalg.norm(v , ord=2)

print("L2 Norm:", l2_norm)

L2 Norm: 5.0


**📏Infinity Norm (Maximum Norm)**

*The infinity norm returns the largest absolute value in the vector.*

In [5]:
inf_norm = np.linalg.norm(v , ord=np.inf)

print("Infinity Norm:", inf_norm)

Infinity Norm: 4.0


**📏 Unit Vectors**

1. *A unit vector is a vector whose magnitude (length) is exactly 1.*

2. *It represents direction only, without changing the vector's orientation.*

Eg:

[3, 4]  -> Original Vector

[0.6, 0.8] -> Unit Vector

*Both point in the same direction, but the second vector has magnitude 1.*

**Why Do We Need Unit Vectors?**

Unit vectors are used in:

- *Machine Learning*
- *Deep Learning*
- *Computer Graphics*
- *Physics*
- *Cosine Similarity*

**They allow us to compare directions independently of magnitude.**

In [11]:
# Create vector
vector = np.array([2, -5, 8])

# Find Magnitude
magnitude = np.linalg.norm(vector)

# Convert to Unit Vector
unit_vector = vector / magnitude

print("Original Vector:", vector)
print("\nMagnitude:", magnitude)
print("\nUnit Vector:", unit_vector)

1.0
Original Vector: [ 2 -5  8]

Magnitude: 9.643650760992955

Unit Vector: [ 0.20739034 -0.51847585  0.82956136]


In [12]:
#Verify Magnitude is 1

print(np.linalg.norm(unit_vector))  # This confirms it is a unit vector.

1.0


**📏 Generalized Lp Norm**

1. *The Lp Norm is a general formula that defines a whole family of norms.*

2. *The L1 Norm, L2 Norm, and Infinity Norm are all special cases of the Lp Norm.*

3. *Instead of having separate formulas, we can use one generalized formula.*

In [13]:
import numpy as np

v = np.array([1, 2, 3])

print("L1 :", np.linalg.norm(v, ord=1))
print("L2 :", np.linalg.norm(v, ord=2))
print("L3 :", np.linalg.norm(v, ord=3))
print("L_infinity :", np.linalg.norm(v, ord=np.inf))

L1 : 6.0
L2 : 3.7416573867739413
L3 : 3.3019272488946263
L_infinity : 3.0


**💡 Key Takeaways**

- *Lp Norm is the generalized form of all norms.*

- *L1, L2, and Infinity Norm are special cases.*

- *The value of p determines how the vector magnitude is measured.*

- *Lp norms are heavily used in Machine Learning, Optimization, and Regularization.*

**📏 Basis Vectors**

- *A basis is a set of vectors that can be used to represent every vector in a vector space.*

- *The vectors in this set are called basis vectors.*

- *Think of basis vectors as the building blocks of all other vectors.*

**Why Are Basis Vectors Important?**

Basis vectors help us:

- *Describe coordinates*

-  *Build vector spaces*

-  *Understand transformations*

- *Learn PCA and dimensionality reduction*

- *Understand embeddings in Machine Learning*

In [15]:
# Create Basis Vector


# 2 D
import numpy as np

e1 = np.array([1, 0])
e2 = np.array([0, 1])

print("e1:", e1)
print("e2:", e2)

v = 3 * e1 + 5 * e2

print(v)

e1: [1 0]
e2: [0 1]
[3 5]


In [16]:
# 3 D

e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

print(e1)
print(e2)
print(e3)

[1 0 0]
[0 1 0]
[0 0 1]


**📏Orthogonal Vectors**

*Two vectors are called orthogonal if they are perpendicular to each other (90° angle).*

*In Linear Algebra, instead of measuring the angle directly, we use the dot product.*

a · b = 0
-> where · represents the dot product.

For two vectors:
-> a = [a₁, a₂]
  b = [b₁, b₂]
The dot product is:  
-> a · b = a₁b₁ + a₂b₂

**Why Are Orthogonal Vectors Important?**

Orthogonal vectors are used in:

- *PCA (Principal Component Analysis)*

Features are transformed into orthogonal directions.

- *Machine Learning*

Helps remove redundancy between features.

- *Singular Value Decomposition (SVD)*

Built using orthogonal vectors.

- *Deep Learning*

Used in matrix decompositions and optimization.

In [17]:
import numpy as np

a = np.array([1, 1])
b = np.array([1, -1])

dot_product = np.dot(a, b)

print(dot_product)

0


**💡 Key Takeaways**

-  *Orthogonal vectors are perpendicular.*

-  *Their dot product equals 0.*

-  *Dot Product is the easiest way to check orthogonality.*

-  *Orthogonality is a core concept behind PCA, SVD, dimensionality reduction, and many Machine Learning algorithms.*

**📏Matrices**

- *A matrix is a rectangular arrangement of numbers organized into rows and columns.*

- *A matrix is essentially a collection of numbers stored in a tabular format.*

**Why Are Matrices Important?**

Matrices are used everywhere in:

- *Data Science*

- *Machine Learning*

- *Deep Learning*

- *Computer Vision*

- *Recommendation Systems*

*Almost all ML algorithms work with data represented as matrices.*

In [19]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

print(A)

[[1 2]
 [3 4]]


In [20]:
print(A.shape)

(2, 2)


In [21]:
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(B.shape)

(2, 3)


In [22]:
# Matrix Addition

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A + B)

[[ 6  8]
 [10 12]]


In [23]:
# Matrix Subtraction

print(B - A)

[[4 4]
 [4 4]]


In [24]:
# Matrix Transpose

print(A.T)

[[1 3]
 [2 4]]


In [25]:
# Matrix Multiplication

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A @ B)

[[19 22]
 [43 50]]


**💡 Key Takeaways**

- *Matrix = rows × columns*

-  *Shape tells dimensions*

-  *Addition/Subtraction require same shape*

-  *Transpose swaps rows and columns*

-  *Matrix multiplication is fundamental in ML and Deep Learning*

-  *Most datasets are stored as matrices*

**📏Generic Tensor Notation**

*A tensor is a generalized mathematical object that extends scalars, vectors, and matrices.*

*Think of tensors as containers for numerical data with different numbers of dimensions.*

Scalar  -> Rank 0 Tensor

Vector  -> Rank 1 Tensor

Matrix  -> Rank 2 Tensor

Tensor  -> Rank 3 or Higher

In [26]:
import numpy as np

# Rank 0 Tensor - Scalar
scalar = np.array(10)

# Rank 1 Tensor -  Vector
vector = np.array([1, 2, 3])

# Rank 2 Tensor - Matrix
matrix = np.array([[1, 2], [3, 4]])

print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)

0
1
2


**📏Higher-Rank Tensors**

*Any tensor with rank 3 or more is called a higher-rank tensor.*

These are heavily used in:

- *Deep Learning*
- *Computer Vision*
- *NLP*
- *Generative AI*

**Why Are Tensors Important?**

Frameworks like:

- *NumPy*
- *TensorFlow*
- *PyTorch*

store and process data using tensors.

*Every image, video, embedding, and neural network input is represented as a tensor.*

📏**Image Tensor Example**

*A color image consists of:*
*Height × Width × Channels*

In [27]:
image = np.random.rand(224, 224, 3)

print(image.shape)

# 224 = Height
# 224 = Width
# 3   = RGB Channels

(224, 224, 3)


**📏Video Tensor Example**

*A video is a collection of image frames.*
*Frames × Height × Width × Channels*

In [28]:
video = np.random.rand(10, 224, 224, 3)

print(video.shape)

# 10  = Frames
# 224 = Height
# 224 = Width
# 3   = RGB Channels

(10, 224, 224, 3)


**💡 Key Takeaways**

- *Scalar = Rank 0 Tensor*

-  *Vector = Rank 1 Tensor*

-  *Matrix = Rank 2 Tensor*

-  *Tensor = Rank 3 or Higher*

-  *Rank = Number of Dimensions (Axes)*

-  *Images and videos are represented using higher-rank tensors*

- *Tensors are the fundamental data structure in Deep Learning*

# 🎯 Conclusion

**In this notebook, I explored fundamental Linear Algebra concepts that form the mathematical foundation of Data Science, Machine Learning, and Artificial Intelligence.**

**I learned how norms measure vector magnitude, how unit vectors represent direction, and how generalized Lp norms extend distance measurements. I also explored basis vectors and orthogonal vectors, which are essential for understanding vector spaces, dimensionality reduction, and algorithms such as PCA.**

**Additionally, I practiced working with matrices, including their shapes, transpose operations, and matrix multiplication. Finally, I gained an understanding of tensors and higher-rank tensors, which serve as the core data structures used in modern Deep Learning frameworks.**

**This learning journey strengthened my understanding of how mathematical concepts are translated into practical implementations using Python and NumPy, providing a strong foundation for advanced topics in Machine Learning, Deep Learning, Computer Vision, and Generative AI.**


🌟 **Learning Outcome**

***By completing this notebook, I gained hands-on experience with fundamental Linear Algebra concepts that serve as building blocks for Machine Learning, Deep Learning, Computer Vision, Natural Language Processing, and Data Science applications.***